### ISSUE TITLE
Include scripts should be conditionally based on fields used

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#136]
CMB2 Loads an immense amount of inline script tags when used with front end forms.  Even when none are necessary.  Im using it to generate a simple review form, and WOW - Thats a lot of inline scripts.  Is there a way to disable the inclusion of the wordpress media template?  Its kinda huge, and is unnecessary,

**Comment by GregLancaster71** [comment]
Edit: For now I wrapped line 221 in `helper-functions.php` with `if ( is_admin() ) {}`.  Now before I upload this to a live site, is there any reason this would break anything?

**Comment by jtsternberg** [comment]
Yes, don't edit the core files, or you'll break it for other plugins/themes that are depending on the library. Are you sure you mean line 221? https://github.com/WebDevStudios/CMB2/blob/master/includes/helper-functions.php#L221
Also, can you be more specific about which scripts are loaded? I agree, this should not happen unless the field types you add need them.

**Comment by GregLancaster71** [comment]
My Mistake - Its this line : `CMB2_hookup::enqueue_cmb_js();`.

**Comment by jtsternberg** [comment]
I just added a simple text field to the front-end, and yah, I got the whole WordPress media setup enqueued. Definitely a bug. But again, please do not edit the core files. It is a bad idea for many reasons. I've included a filter for the [JS](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_hookup.php#L380) and the [CSS](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_hookup.php#L367) enqueueing so you can at least block them that way.
```php
function maybe_not_enqueue_cmb_js( $do_enqueue ) {

	/**
	 * Make sure to set a limited scope for your condition so you don't
	 * disable JS for every plugin/theme that may use this feature.
	 */
	$my_conditions_are_matched = ( ! is_admin() && 'custom-post-type' == get_post_type() ); 

	if ( $my_conditions_are_matched ) {
		// Ok, then, don't enqueue the JS
		return false;
	}

	return $do_enqueue;
}
cmb2_enqueue_cmb_jsadd_filter( 'cmb2_enqueue_js', 'maybe_not_enqueue_cmb_js' );
``` 
We'll need to work on making these script enqueues more conditional in the future.

**Comment by AlchemyUnited** [comment]
@jtsternberg - I can make a go at this if you can prehaps fill me in with where to start, where to look, etc. That said, while I understand it's gonna create a larger file, can't all the js just be jammed together? swallow that once and then not have to worry about it? I was just reading someone's article and basically it came down to: splitting hairs didn't beat just one larger payload one time. Unless of course we're talking about something massive. 

That said...

Is there anywhere that maps form component to js files required for that component? that would make sense (I think). Then it's just a matter of saying "what's on this page" and "okay then, enqueue these (and not these)." at least that's how I think I would want to approach it. 

fwiw, I do my enqueing with arrays. That is, I have all the details for each script or CSS in an array, and then I run that thought a method that does the actual enqueueing. The point is, that kinda makes manipulation of that easier since the enqueue'ing is done programatically and not hardcoded. One of the properties / fields in my array is active. It's a simple bool switch for turning stuff on and off. Yeah, I've run into this kinda thing before ;)

LMK

Thx
mfs
