### ISSUE TITLE
admin_menu action hook

### ISSUE THREAD

**Issue by inspiraaz** [WebDevStudios/CMB2#161]
Is there any special reason why admin_menu hook is used to add metaboxes.
Isn't the add_meta_boxes hook more appropriate ?

**Comment by inspiraaz** [comment]
Since this question makes no sense let me explain the issue i have.

I have a custom metabox ( not cmb2 ) that is initialized with add_meta_boxes hook.
And i want page elements to appear in this order...

content editor
my metabox
cmb2 metabox
other stuff ( author... )

I tried to change metabox priority and just can't set this order.
If cmb2 used the same hook ( add_meta_boxes ) i could set this order with hook priority.

**Comment by jtsternberg** [comment]
This is a great question. I dug into git history, and it turns out, that hook was used from [day one, the first commit](https://github.com/WebDevStudios/CMB2/commit/cfd80fc75784f1fe2fd53220f3a9b9507e696567#diff-e9fa0d13b445ed0246ee0003db4374d6R82). My guess is that the `'add_meta_boxes'` was not very well-known at that point. I'll update in trunk to use this correct hook, and (if it doesn't break anything), will be in the next release.
