### ISSUE TITLE
Change base url without having to reselect image from media 

### ISSUE THREAD

**Issue by con322** [WebDevStudios/CMB2#200]
Apologies if this info is in the documentation but I couldn't find it.

When moving from localhost to say live site how can I change the base url of files as currently when I go it I have to go the file field and reselect the image from the media section as the base url still reads localhost is there a global setting in CMB2 where by you can set this url.

:)

**Comment by jtsternberg** [comment]
the file field saves the attachment id as well, so as long as you're doing a database import/export as well as migrating all the files, you should be able to use that w/ no issues. See the documentation: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#file

BUT to answer your question, there is not CMB2 setting to change this. It's probably best to replace those urls in your database as they will also be the localhost urls for any images you've used in the post-content as well.

**Comment by elbsurfer** [comment]
@jtsternberg 

I have the same issue - I moved the site from development to production and the URLs in the postmeta table have the old baseurl. I can not do a sql to change all URLs in postmeta, because the array structure which is like this `s:16:"_fys_gb_gallerie";a:1:{i:839;s:82:"http://wp10...` has information included how long the URL is -> s:82. When I change the URL now with a SQL statement the information about the array length is wrong and will possibly break, right? Is there no function to re-index the contents?

Is your suggestion then to use always the image id in the file list meta box and not the absolute URL?

**Comment by tw2113** [comment]
@elbsurfer You're going to want to find a technique for migrating domain URLs that takes serialized data into account. Straight SQL statements likely aren't going to.

This looks like a solid tutorial for a better migration process http://www.codeforest.net/how-to-migrate-wordpress-site
