### ISSUE TITLE
Custom field in media page.

### ISSUE THREAD

**Issue by mattkrupnik** [WebDevStudios/CMB2#235]
Hi

Is possible to add custom cmb2 field to media page for example categories.

Edit ;)

```php
'object_types' => array('attachment')
```

Regards
Matt

**Comment by monecchi** [comment]
I've been trying to achieve the same thing. What about setting up a field for a custom taxonomy which belongs to a custom post_type? 

`'object_types' => array('portfolio_categories') // this is the custom taxonomy`
`'taxonomy' => 'portfolio_categories', // also no effects if I set this`

Thanks in advance.
Adriano Monecchi

**Comment by jtsternberg** [comment]
The code @mattkrupnik has is how you add to the media page.
There is a demo in example-functions.php for adding taxonomy/term metaboxes: https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L535-L541

**Comment by monecchi** [comment]
@jtsternberg Thanks for pointing out the example function. I've just updated CMB2 to its latest version (2.2.0) and I've just copied the example function for adding taxonomy/term metaboxes. I modified it a bit to match my theme's setup with the right prefix and so on, however, I just can't get it to work.

My theme uses a custom post_type registered as "food_menu",  as also two custom taxonomies that act like categories and tags, "food_menu_categories" and "food_tags", both work as intended with my custom post_type, but when I try to set up the metabox, nothing shows under the taxonomy edit page...

Here's how I've set it up:

    `'object_types'     => array( 'term' ), // Tells CMB2 to use term_meta vs post_meta`
    `'taxonomies'       => array( 'food_menu_categories', food_tags' ), // Tells CMB2 which taxonomies should have these fields`

Am I missing something else?

**Comment by jtsternberg** [comment]
Which version of WordPress are you on?

**Comment by monecchi** [comment]
My WordPress install is 4.5 - I've just updated it, but before it I was
running the 4.4.2 version with a long the CMB2 trunk.

I've also updated CMB2 to its latest version, and the issue is all other
type of metaboxes my theme uses are working, even some more complex ones
such as repeating groups. Anyway, the term metabox simply doesn't show up
when editing my custom taxonomy under WP Admin.

Thanks for checking it though.

Adriano Monecchi

Em sexta-feira, 22 de abril de 2016, Justin Sternberg <
notifications@github.com> escreveu:
