### ISSUE TITLE
time_format in field type "text_time"

### ISSUE THREAD

**Issue by svenvonarx** [WebDevStudios/CMB2#282]
In your Wiki i found this in the example of field "text_time": // 'time_format' => 'h:i:s A',

But when I change the format to 24h like this "H:i" or "G:i" it will not affect anything.
The time_format is always the same..

I hope this feature will be fixed soon, or you can tell me what I'm doing wrong now.

Best regards
Sven

**Comment by yivi** [comment]
Ditto that. Can't get 'time_format" to work either.

**Comment by austinjreilly** [comment]
This might help, although I'm not sure: https://github.com/WebDevStudios/CMB2/issues/226#issuecomment-78278448

**Comment by yivi** [comment]
Thanks @austinjreilly, I can see how you could shortcircuit it that way, but it still doesn't solve the underlaying problem (apparently time_format is ignored, and CMB2 will just use the default values). As far as I can see, you'll just be replacing one default for another, right?

On top of that, the wiki is wrong about the format. It shouldn't use the date format from php, but a time format as documented [here] (http://trentrichardson.com/examples/). (Not that it matters, since time_format is ignored anyway).

And for my language (Spanish) the translation file is wrong, so it'll give me times with AM/PM, instead of 24hs as we use in Europe. I'll try to submit a corrected po/mo pair for that at least.

Regards!

**Comment by yivi** [comment]
Fixing the translation strings helps, but doesn't solve the problem either. Not it works, and the timepicker would let me choose the time in 24hs format, but after saving I get this:
![editar_anuncio_ _yosilose_com_ _wordpress](https://cloud.githubusercontent.com/assets/1815039/7509591/e6345310-f492-11e4-8364-075526040deb.png)
The time is correct (I chose 19:20 before hitting save), but not it displays it in 12hs format, and the time picker wont default to the selected time... But I guess data is saved correctly at least.

A bit confusing...

**Comment by yivi** [comment]
Confirmed: Date is saved as "19:20" postmeta, displayed as "7:20 PM" in the metabox (but only after loading the data from the DB), and the timepicker wont choose the correct default value when reading 12hs format from the field and displaying a 24hs format picker...

**Comment by jtsternberg** [comment]
This should be good in [trunk](https://github.com/WebDevStudios/CMB2/tree/trunk). Huge thanks for @yivi's work. Please test.
