### ISSUE TITLE
Shortcodes don't work in a wysiwyg field

### ISSUE THREAD

**Issue by yeahsmaggy** [WebDevStudios/CMB2#292]
Shortcodes don't work in a wysiwyg field but work in regular wordpress body field in pages. Any idea what might be causing this? I'm specifically using formidable forms, but I've also tried with other shortcodes.

**Comment by yeahsmaggy** [comment]
I had to wrap the outputted content with do_shortcode.

**Comment by jalberts** [comment]
Were you not filtering your meta data with `the_content`? That would probably be your better option:

```php
$wysiwyg = apply_filters( 'the_content', get_post_meta( get_the_id(), $prefix . 'wysiwyg_meta_name', true ) );
```

Arbitrarily picked variable and meta data names. But something like that instead. Note that my example uses a `$prefix` variable, instead of how the [wiki example](https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage#display-the-metadata) does it.

**Comment by yeahsmaggy** [comment]
$joya_air_page_meta['writers_text'] = do_shortcode(get_post_meta ( $post->ID, '_jo_air_page_writers_text', true ));

**Comment by jalberts** [comment]
Right, I gotcha. I'm just suggesting that you'll probably want to filter a wysiwyg field through `the_content` instead of using `do_shortcode`.

You'll still get your shortcodes resolved, but you'll also get all [the normal defaults](http://wordpress.stackexchange.com/a/51749) you'd expect from the standard TinyMCE (wysiwyg) editor.

**Comment by jtsternberg** [comment]
Downside to using the `the_content` filter is that it's typically used to output thinks like social sharing icons, and other things that plugins add. Can be a pain.

The codex actually has an example function for doing this type of thing: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#wysiwyg

**Comment by jalberts** [comment]
Good point, and excellent example snippet there!

**Comment by smpdesignmedia** [comment]
I've done this using getting shortocode output by following code : 

$wysiwyg = apply_filters( 'the_content', get_post_meta( get_the_id(), $prefix . 'wysiwyg_meta_name', true ) );

it just want to know, is it the perfect solution for getting shortcode output ?

**Comment by nvminhtu** [comment]
Thanks @yeahsmaggy , the code run well.

**Comment by mahmud-sajib** [comment]
@jalberts got the best solution
Thank You!
