### ISSUE TITLE
Javascript validation of required fields.

### ISSUE THREAD

**Issue by erikdrums** [WebDevStudios/CMB2#352]
I needed support for this type of attribute:
```
 $cmb->add_field( array(
        ...
        'required'   => True,
  ));
```
When submitting the post javascript validation is run on all fields with "required" set to true.
If any are not validated an error is displayed in the top and for each unvalidated field.

The solution is very similar to how https://wordpress.org/plugins/advanced-custom-fields/ handle their validation.

Is this a featured the CMB2 team would like to implement as I might make a pull-request and make it fit into core CMB2?

Any requirements if I did this?

**Comment by jtsternberg** [comment]
We're certainly open to a pull request. For now, you can add the required attribute to the field to have the browser validate it instead. You can do that with the 'attributes' property:
```php
$cmb->add_field( array(
	...
	'attributes' => array(
		'required' => 'required',
	),
));
```

**Comment by erikdrums** [comment]
Yes thanks! I'm aware but this, it does not appear to be working for type='wysiwyg' though (the required attribute isn't set one the textarea element), also it seems a javascript solution might be better for displaying multiple errors.

**Comment by jtsternberg** [comment]
ah, that makes sense w/ the wysiwyg type. If using JS, I would want to make sure we use a common validation UI (maybe bootstrap?) or ensure the UI make sense. I'm definitely open to it. I'm closing because there are already several relevant tickets.
Related:
https://github.com/WebDevStudios/CMB2/issues/100
https://github.com/WebDevStudios/CMB2/issues/62
https://github.com/WebDevStudios/CMB2/issues/61
