### ISSUE TITLE
Allow html inside a field type: text

### ISSUE THREAD

**Issue by apokyro** [WebDevStudios/CMB2#443]
Hello,
I'am try to find a way to allow html tags inside a field type text.
Is that possible?

Thanks in advance

**Comment by JayWood** [comment]
You'll want to filter that field yourself.  By default iirc the value is ran through `sanitize_text_field()`

See about sanitization here: [cmb2_sanitize_{field-type}](https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types#step-2-cmb2_sanitize_field-type)

**Comment by apokyro** [comment]
Thanks @JayWood . It works!!

For anyone who want to use this method:
```
function cmb2_sanitize_text_field_callback( $override_value, $value ) {
    //convert square brackets to angle brackets
    $value = str_replace('[', '<', $value);
    $value = str_replace(']', '>', $value);
    return $value;
}
add_filter( 'cmb2_sanitize_text_field', 'cmb2_sanitize_text_field_callback', 10, 2 );
```
In other words if you type [br] inside a text field, it will output `<br>`.

**Comment by jtsternberg** [comment]
@JayWood's suggestion is not what I would recommend for the built-in field types (it's intended use is for handling sanitization for custom field types, like in the docs Jay linked to), because now you're modifying the sanitization for **all** CMB2 'text' field types. Keep in mind, just like modifying WordPress filters, your modifications could have unintended consequences for plugins/themes depending on those things to be in place, and that your project may not be the only thing depending on CMB2.

The best way to accomplish what you are trying to do is to use the [`'sanitization_cb'` field parameter](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#user-content-sanitization_cb) on a field-by-field basis. This will ensure you are **only** modifying the sanitization for your specific field(s).


```php
$cmb->add_field( array(
	'name'            => __( 'Test Text', 'cmb' ),
	'id'              => 'wiki_test_text',
	'type'            => 'text',
	'sanitization_cb' => 'prefix_sanitize_text_callback', // function should return a sanitized value
) );
```

The sanitization callback:
```php
function prefix_sanitize_text_callback( $value, $field_args, $field ) {

	/*
	 * Do your custom sanitization. 
	 * strip_tags can allow whitelisted tags
	 * http://php.net/manual/en/function.strip-tags.php
	 */
	$value = strip_tags( $value, '<p><a><br><br/>' );

	return $value;
}
```

**Comment by yeasin62** [comment]
Thats works. Thank you so much.

**Comment by monecchi** [comment]
@jtsternberg Thanks for pointing out the importance of custom sanitization on a per field basis.
