### ISSUE TITLE
Meta  Boxes not showing up

### ISSUE THREAD

**Issue by teslimni** [WebDevStudios/CMB2#484]
Hey guys will be glad for your help. Trying to use CMB2 to create options page for a theme am working on. I copied the provided example with no changes just to make sure it shows on screen before I start editing. Only the page title shows and nothing else. I have tried all the little PHP stunts I can but to know avail. 
Thanks for your help in advance.

**Comment by humidca** [comment]
@teslima Have you had any luck with this? We are running into the same issue.

**Comment by jtsternberg** [comment]
If you're using the options page snippet from the CMB2 Snippet Library, you're best bet is to open an issue there.

**Comment by teslima** [comment]
@humidca not at all. I have given up on CMB2 since and try to roll out my own options page. Talk of re-inventing the wheel. But when the available wheel is not serving you, you got to move ahead creating your own. Thanks to the codex and Google, O managed to roll one out. Though still refactoring it.

**Comment by humidca** [comment]
@teslima I understand what you mean. 

If you do decide to jump back to CMB2 we came across this https://github.com/WebDevStudios/CMB2-Snippet-Library/issues/21
Which helped us get back on track. Apparently the latest options page snippet was based on the trunk version of CMB2. 

Using https://github.com/WebDevStudios/CMB2/tree/trunk we managed to make the options page work for us.

**Comment by teslima** [comment]
@humidca Thanks so much. I definitely will come back to it with what you showed me. I am proud to be a web developer because of this kind behaviour you just showed me. The spirit of sharing tips and solutions among developers make me believe in the kindness of humanity. Thanks sooo much. 
I am currently working on creating a simple theme framework with sass, compass, susy and the theme hook alliance idea of theme hook. I will be relying heavily on third party systems to make this happen. Sure, CMB2 will be part of it.

**Comment by jtsternberg** [comment]
Are we good here?

**Comment by humidca** [comment]
I believe so.

**Comment by jtsternberg** [comment]
:thumbsup: If you see more issues w/ the options page, please open an issue on the snippets repo. Thanks.
