### ISSUE TITLE
noob alert: extend categories, how? 

### ISSUE THREAD

**Issue by rob-ot-dot-be** [WebDevStudios/CMB2#547]
second week wp, bare with me :)

How can I extend categories? 

this doesn't do much, I presume a category is not a post type in wordpress, right? 
'object_types'  => array( 'page', 'category' ), // Post type.

**Comment by joshuadavidnelson** [comment]
You're looking to add fields to a taxonomy (category/tag), right? Check out [CMB2_Taxonomy](https://github.com/jcchavezs/cmb2-taxonomy) (be sure to use the current github repo directly, the current/previous official releases are missing a critical `function_exists` check that breaks in WP 4.4, since term meta is now in core).

**Comment by rob-ot-dot-be** [comment]
perfecto mundo !

**Comment by jtsternberg** [comment]
Term meta will be in the next CMB2 release and is available in the trunk branch. I suggest using that instead of a 3rd party lib.

**Comment by joshuadavidnelson** [comment]
:+1:

**Comment by joshuadavidnelson** [comment]
@rob-ot-dot-be see: https://github.com/WebDevStudios/CMB2/blob/trunk/example-functions.php#L525

**Comment by rob-ot-dot-be** [comment]
double perfecto mundo !
