### ISSUE TITLE
No matter what I set the Priority to it always shows up last

### ISSUE THREAD

**Issue by contempoinc** [WebDevStudios/CMB2#548]
No matter what I set the Priority to it always shows up last in the mix, screenshots:

Set as Core
Code - http://cl.ly/1e3b1v2W131J
Admin -http://cl.ly/0l1y0t321b0U

Set as High
Code - http://cl.ly/0B051x2B0i0C
Admin - http://cl.ly/1l2T2F0H232V

I've also set the context to normal but I can't get it to move up above anything but author?

Is this a known issue in the current release, or?

**Comment by contempoinc** [comment]
Just looking at the admin_hooks() function in CM@_hookup.php the priority variable is only used for user metaboxes, or am I reading this wrong? Code screenshot http://cl.ly/1B2n2e311h3G

**Comment by rfmeier** [comment]
@contempoinc Since the title text box, slug, and post content editor are all hard-coded, you won't be able to get above those.  https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-form-advanced.php#L541

While testing using `'context' => 'side'` I was able to get the custom meta box to the top.  Could it be possible other meta boxes just got on the 'stack' before yours?

**Comment by tw2113** [comment]
Related #77

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
