### ISSUE TITLE
Base 64 in the css file

### ISSUE THREAD

**Issue by colincsd** [WebDevStudios/CMB2#651]
Carefull this thing will turn your wp into a spammer, see the base 64 in background images in the css

**Comment by williamsba** [comment]
The base64 you see is actually just an image encoded into a data-uri, which is totally safe and saves keeping an image on the filesystem. The image encoded is this one:

https://www.dropbox.com/s/fi4r0lx2uuyko1b/Screenshot%202016-05-19%2013.57.19.png?dl=0

Here's a good article by Otto (who maintains the WP.org website) on why this is a good method http://ottopress.com/2011/a-good-use-for-base-64-encoding-data-uris/ 

It's possible you have a security scanner on your website that shows this as a security warning, because they look for anything using base64, but in this case it's completely safe and a recommended solution.

Thanks for reporting regardless. We absolutely want to make sure any code we release is solid from a security standpoint.

**Comment by bradp** [comment]
Closing this. @colincsd if you want to reopen this, please see these 100,000 other repos first, as they have the same "issue". 

https://github.com/search?o=desc&q=%22data%3Aimage%2Fpng%3Bbase64%22&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93
