### ISSUE TITLE
I edited the wiki to include text_date field type, was that wrong?

### ISSUE THREAD

**Issue by twoelevenjay** [WebDevStudios/CMB2#669]
I edited the wiki to include text_date field type, was that wrong? But I see `text_date` is referenced as an alias under `text_date_timestamp`. Is it not possible to have a date field that actually saves the formatted date to the DB rather than the time stamp anymore?

https://github.com/WebDevStudios/CMB2/wiki/Field-Types#text_date

**Comment by jtsternberg** [comment]
> Is it not possible to have a date field that actually saves the formatted date to the DB rather than the time stamp anymore

That is correct. A timestamp is far more versatile.

You can convert a timestamp to any format using [`date()`](http://php.net/manual/en/function.date.php).

Or alternatively using CMB2 methods:
```php
$formatted_date = cmb2_get_field( $cmb_id, $field_id, $object_id )->get_timestamp_format();
```
I've updated the wiki. I don't think there's a reason to have a separate line for each since they are the same.
