### ISSUE TITLE
Conditional logic, 'show_on' filter, based on the selected option in the Format box

### ISSUE THREAD

**Issue by VladNov** [WebDevStudios/CMB2#717]
### Expected Behavior:

Show/Hide fields based on an option selected in the Format box.

For example i've added 'file_list' field which i want to show only if the Gallery option was selected in the Format box.

There is such filter, but the problem is that it's only works if the post was Published or Updated
https://github.com/orenhavshush/cmb2-post-format-show_on-filter
### Actual Behavior:

All fields are visible for all Formats.
### CMB2 Field Registration Code:

Just regular 'file_list' field.

**Comment by tw2113** [comment]
Some thoughts.
1. I believe it would work as well with saved drafts, since I believe it'd work based on saved meta about the post.
2. You'd probably want to raise the issue with that plugin author more, since it's not one that WebDevStudios did up ourselves, unless that's just an example of a similar thing and you're using CMB2 core only at the moment.

**Comment by jtsternberg** [comment]
You might want to see if that's supported by https://github.com/jcchavezs/cmb2-conditionals

**Comment by tw2113** [comment]
Any changes on your end @VladNov ?

**Comment by VladNov** [comment]
Hi @tw2113, unfortunately i had no time to sit and resolve it.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
