### ISSUE TITLE
Remove Base Slug

### ISSUE THREAD

**Issue by needtakehave** [WebDevStudios/CMB2#758]
I tried to use a plugin to remove the base slug of the custom post type that the plugin adds. Example. I have a custom post type called reviews (that's the slug) so the url is [](http://www.booksbytheton.xyz/reviews/whatever/) instead of the usual [](http://www.booksbytheton.xyz/whatever/) . So I installed a plugin from here - [](https://wordpress.org/plugins/simple-post-type-permalinks/) which removes the base slug. It does work. It works just like Wordpress, where in the Permalinks section, it adds an extra section where you can customize every new custom post type just like when you start Wordpress, and you can either select "Default" or the various different ways that Wordpress has or the "custom" and make your own. So I made my own, without the slug. Then it broke -- and it wasn't the plugin, it was a conflict, I believe, somehow with CMB2. Because as soon as I went back to "Default" (with the plugin still installed/activated, just set to Default) the pages went back to normal. See, when I set them to a custom setting, the pages came up as a 404, not found. Is there any way to have it so I can use the plugin and/or a code to make it so I can remove the slug some other way?

**Comment by tw2113** [comment]
I'm struggling to think how CMB2 would be having anything to do with this, since it has nothing to do with permalinks and rewrite rules. Can you confirm whether or not the same 404 occurs with CMB2 disabled?

Based on my experiences/general knowhow with custom post types, chances are the url has nothing to query for posts with anymore, thus the 404 error.
