### ISSUE TITLE
CMB2 Plugin install failed.

### ISSUE THREAD

**Issue by cichairs** [WebDevStudios/CMB2#774]
Can anyone help - trying to install the plug in but keep getting this message. New to this so unsure how to go about trying to solve the issue. 

Destination folder already exists. /var/www/vhosts/contractinteriors.co.uk/contractfurnituremanufacturers.co.uk/wp-content/plugins/cmb2/

Plugin install failed.

**Comment by tw2113** [comment]
sounds like there's a folder named "cmb2" already, but the folder is empty. Probably have to log in via FTP and either remove the folder and re-install via WP admin, or just upload it manually while still connected via FTP.

Closing the issue aspect since it's not an issue with the code itself, but you can still comment afterwards, as necessary. Also note that our support area for questions like this is at http://wordpress.org/support/plugin/cmb2 which we actively monitor.

**Comment by cichairs** [comment]
Thanks, all sorted now.
