### ISSUE TITLE
Google font metaboxes?

### ISSUE THREAD

**Issue by fakeartist** [WebDevStudios/CMB2#792]
It would be great if a google font metabox could be found in the list of available metaboxes. It could let you choose from an available web font, the font size, weight etc. Any ideas on this?

**Comment by jtsternberg** [comment]
This would be a pretty great custom field type, but it's not something we would include in CMB2 core. If you end up developing a custom field type, let us know.

**Comment by eduplessis** [comment]
I've made a custom field for typography ... you can check it 
[cmb2-typography](https://github.com/eduplessis/cmb2-typography)

**Comment by tw2113** [comment]
hey @eduplessis 

Just gave it a quick test run and I had a couple thoughts. Both presently revolve around the `if_fields` method. First up is that it tries to type hint against string. I have no issue with that as a whole, but it will be important to note that the plugin you have requires PHP7 or higher. That way the scalar type hints will be available.

Second up is that I'm not sure about the logic inside `if_fields` because I was only specifying a couple items from the available list, and they're still all showing up. This tells me the if statement at https://github.com/eduplessis/cmb2-typography/blob/master/class-cmb2-render-typography-field.php#L77 is always returning true.

Beyond that though, it definitely looks like it has potential to be a good item to add to the 3rd party resources.

**Comment by eduplessis** [comment]
@tw2113 for the `if_fields`  it's removing the field only if you put it at false... and it's true by default
So if you don't specify fields you gonna have all the fields.

And for the "type hint against string" i've removed it... :)

**Comment by tw2113** [comment]
Ah, defaults to all, and to have any removed, set those to false. Gotcha. Perhaps some notes about that in the readme, to help avoid confusion.

Nice job otherwise.
