### ISSUE TITLE
Adding text field to execute javascript code

### ISSUE THREAD

**Issue by kyoukhana** [WebDevStudios/CMB2#814]
Lets say I want to add a field called custom javascript.  How do I display that code without WordPress parsing the code so that it doesn't execute.

**Comment by tw2113** [comment]
Personally, I think I'd end up going the route of providing a way to store a URL to an external JS file, and then in a callback on `wp_enqueue_scripts`, fetch that url and do a standard enqueue at that point. Instead of trying to deal with html character encoding issues and the like.

This would allow you to load the js files only when on the intended page.
