### ISSUE TITLE
New filter: taxonomy select labels

### ISSUE THREAD

**Issue by allysonsouza** [WebDevStudios/CMB2#890]
I'm working on a project that I have to show additional information into the select taxonomy field, displaying the term name but also a term meta field. I think this should be usefull for other developers, so, maybe we can add a new filter in select taxonomy labels?

I've changed my `CMB2_Type_Taxonomy_Select` class adding this filter:

`57. 'label'   => apply_filters( 'cmb2_taxonomy_select_label', $term->name, $term ),`

Thanks!

**Comment by jtsternberg** [comment]
You can already modify the term name by overloading the `$term-name` property using the `get_terms` filter. It will be a bit more work, but since it's already possible, at this point, i'm not inclined to add another filter. There are also more in-depth ways to modify this behavior for your own use-case by specifying your own `'render_class'` (described here: [releases/tag/v2.2.4](https://github.com/WebDevStudios/CMB2/releases/tag/v2.2.4)).

And finally, it's not a good idea to modify the core of the plugin, for normal reasons, but also because there is no guarantee YOUR version is the one that will be loaded ([for more details on that](http://jtsternberg.github.io/wp-lib-loader/)).

**Comment by allysonsouza** [comment]
Thanks @jtsternberg,

I didn't considered the use of WordPress own filters, I'll try it.

I know it's not good to change the core of plugins or WordPress, but being me an "old monkey" (how we say in Brazil - means experienced person), I was making it for my own risk for a hotfix only.

And thanks for the amazing job with CMB2.
