### ISSUE TITLE
Feature Request - Presets for colorpicker

### ISSUE THREAD

**Issue by jamiechong** [WebDevStudios/CMB2#96]
The colorpicker is very handy. A nice extension to it would be to offer a palette of preset colors to choose from. This would show little squares of colors that can be clicked to quickly choose a color. Of course, the admin could also customize the color. Just use the existing `options` setting:

    array(
        'type' => 'colorpicker',
        'options' => array('#ff00ee', '#00ff00', '#00bbff'),
    )

**Comment by efoula** [comment]
Hello,
How to create a custom colour palette without showing up all the colours of the colour picker, I just want to show up a specified number of colours for the admin !!!??

**Comment by benjaminmueller** [comment]
This feature has since been released and you can now modify the colorpicker's default options. I have updated the documentation for the colorpicker field and added a code example as well.

You can find that information here [https://github.com/WebDevStudios/CMB2/wiki/Field-Types#colorpicker](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#colorpicker)

**Comment by jtsternberg** [comment]
thank you @benjaminmueller!

**Comment by efoula** [comment]
Thank you so much, appreciated.
